Repository imsi32/yatline.yazi, pull requests merged in 2024-07, with the labels that each got.

#3 [FEAT] Enumerations And Documentation For Component Setup
  init.lua
Labels: documentation, enhancement

#4 [FIX] Missing Component Type Added
  init.lua
Labels: bug

#5 [FEAT] String Based Components Refactored
  init.lua
Labels: documentation, enhancement

#6 [FEAT] Automatic Configuration For String Based Components
  init.lua
Labels: documentation, enhancement

#7 [FEAT] Automatic Configuration For Line Based Components AND [FEAT] Multi-Colorizable Components
  init.lua
Labels: documentation, enhancement

#8 [UPDATE] Automatic Configuration
  README.md
  init.lua
Labels: documentation, enhancement

#9 [FEAT] Disabling Empty Components
  init.lua
Labels: bug, enhancement

#10 [FEAT] More Basic Components Implemented
  init.lua
Labels: documentation, enhancement

#11 [UPDATE] More Components
  README.md
  init.lua
Labels: bug, documentation, enhancement

#12 [FIX]: add missing parenthesis
  README.md
Labels: bug

#14 [FEAT] Configuration For Background Of Both Lines
  init.lua
Labels: documentation, enhancement

#15 [FEAT] More Advanced Separator Connection
  init.lua
Labels: documentation, enhancement

#16 [FEAT] Displayment of Header-line and Status-line
  init.lua
Labels: enhancement

#17 [Update] Simplicity
  init.lua
Labels: documentation, enhancement

#18 [FEAT] Default Values
  init.lua
Labels: enhancement

#19 [FEAT] Theme Import Support
  init.lua
Labels: enhancement

#20 [UPDATE] Customization
  init.lua
Labels: enhancement

#22 [FEAT] Add-On Support For Components
  init.lua
Labels: enhancement

#23 [FEAT] Add-On Support For Component Types
  init.lua
Labels: enhancement

#24 [FEAT] Components Configuration Refactored
  init.lua
Labels: documentation, enhancement

#25 [FIX] Configless Initialization
  README.md
  init.lua
Labels: bug

#26 [FEAT] Shortened Paths
  init.lua
Labels: enhancement

#27 [FEAT] Disabled Unused Functions
  init.lua
Labels: enhancement

#28 [UPDATE] Enlarged
  README.md
  init.lua
Labels: bug, documentation, enhancement
